=== marcolongol/marcolongo.cloud/libs/common-ui/src/assets/social-auth-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "autoLogin": {
      "description": "Enable auto login",
      "type": "boolean"
    },
    "lang": {
      "description": "Sets the language of the social login buttons",
      "type": "string"
    },
    "googleClientId": {
      "description": "Google client ID",
      "type": "string"
    },
    "googleInitOptions": {
      "description": "Google init options",
      "type": "object",
      "properties": {
        "oneTapEnabled": {
          "description": "Enable Google One Tap",
          "type": "boolean"
        },
        "scopes": {
          "description": "Google scopes",
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "prompt_parent_id": {
          "description": "Google prompt parent ID",
          "type": "string"
        },
        "prompt": {
          "description": "Google prompt",
          "type": "string",
          "enum": ["", "none", "consent", "select_account"]
        },
        "additionalProperties": false
      }
    },
    "facebookClientId": {
      "description": "Facebook client ID",
      "type": "string"
    }
  },
  "required": ["autoLogin", "lang"],
  "anyOf": [
    {
      "required": ["googleClientId"]
    },
    {
      "required": ["facebookClientId"]
    }
  ]
}

=== marcolongol/marcolongo.cloud/libs/common-ui/src/assets/social-auth-config.json
{
  "$schema": "social-auth-config.schema.json",
  "autoLogin": false,
  "lang": "en",
  "googleClientId": "658370247170-dah1l76tmrb7gci7s1c3blkecnov7hip",
  "googleInitOptions": {
    "oneTapEnabled": false,
    "scopes": ["email"],
    "prompt_parent_id": "google-signin",
    "prompt": "select_account"
  },
  "facebookClientId": "1477524642962896"
}
